### ISSUE TITLE
Tracking issue for Project Flara Progress

### ISSUE THREAD

**Issue by natasria** [flaravn/flara#6]
# [project-flara/project-flara](https://github.com/project-flara/project-flara)
- [ ] Startup screen
  - [x] Initial prototype implementation
  - [ ] Tween animation using `bevy_tweening`.
- [ ] Title screen
 - [x] Initial prototype
 - [x] Design direction 
 - [ ] Branding for "Fiana Fortressia" and project logo
- [ ] Startup dialogs
  - [ ] Tutorials
  - [ ] Other custom startup dialogs? (RFC needed)
- [ ] Main menu
  -  [ ] Locations map
   - [ ] Buttons
   - [ ] Main menu interactions (RFC needed)
- [ ] Level Selector
- [ ] Gameplay
   - [ ] What genre and mechanics? (RFC needed)
- [ ] Story
   - [ ] Story prototype (RFC needed)
# [project-flara/bevy-rpg](https://github.com/project-flara/bevy-rpg)
- [x] Moving text
- [x] Disable and enable plugin trough ActiveState
- [ ] Control buttons
  - [ ] Skipping dialog
  - [ ] Skipping all dialogs
  - [ ] Speeding up
  - [ ] See dialogs in a chat view
  - [ ] Minimize view
- [ ] Dialog types 
 - [x] Text dialog
 - [ ] Option picker dialog
 - [ ] Text form dialog  
- [ ] Avatars
 - [ ] PNG avatars
 - [ ] Inochi2D avatars support 
- [ ] Audio
 - [ ] Character voice over support
 - [ ] Music and sound effects
